### ISSUE TITLE
Is the QUIC client runnable ?

### ISSUE THREAD

**Issue by bharatkrishna** [ami-GS/gQUIC#1]
I've been following this project for a while as this is the only QUIC client in Go that is being actively deveopled. I'd like to know is the client is capable of making requests to a QUIC server. 

Also is support for QUIC crypto protocol planned(if it isn't already there)?

Thanks!

**Comment by ami-GS** [comment]
Hi @bharatkrishna 

Sorry this QUIC client is still in progress, it doesn't work properly.
And I plan to implement QUIC crypto, but it will be in the future because I'm not familiar with it. I have to study.

Thanks for your comment!!
